# Generated by Django 3.1.1 on 2020-09-19 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sources',
            new_name='Source',
        ),
    ]
