# Generated by Django 3.1.1 on 2020-09-22 17:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_remove_article_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='label',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
