# Generated by Django 3.1.1 on 2020-09-23 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_source_label'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['url'], name='article_art_url_8775f8_idx'),
        ),
    ]
