# Generated by Django 3.1.1 on 2020-09-23 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_auto_20200923_1005'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['header'], name='article_art_header_c906bc_idx'),
        ),
    ]
