# Generated by Django 3.1.1 on 2020-09-20 10:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200919_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersource',
            name='label',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
